name: Analyze and Generate Changelog

on:
  push:
    branches:
      - main
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Semantic-Release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}